[cursor.style]
blinking = "Off"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Underline"

[font]
size = 10

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = '([0-9a-f]{12,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})'

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"
